### PR TITLE
Angle based FOV, also added 'attack teammate' option

### PR DESCRIPTION
**Pull request by w3bn00b**

### CODE REVIEW

**Comment by Teklad** [comment]
I'll need some time to test this.  Is it like a mode somewhere between nearest and and distance based fov?  I'm not super familiar with CSGO yet, lol.

**Comment by Teklad** [comment]
Okay.... tested... there seems to be an issue though.  It doesn't want to work at all unless I'm like right up against my opponent.

**Comment by w3bn00b** [comment]
well, i was not checking viewangle.
now it should work

**Comment by Teklad** [comment]
Gonna go ahead and merge this now.  If you decide to do recoil control, try to do it outside of the Aim() function in its own section so there's no redundant code.

**Comment by Teklad** [comment]
I'm working hard on a linux offset dumper at the moment that I'm trying to get on par with Hazedumper on Windows so the barrier for entry writing hacks on Linux isn't so high.

**Pull request merged**
