### PR TITLE
[WIP]Hitsound implement

### PR DESCRIPTION
**Pull request by w3bn00b**
ignore the typo on the branch xD

### CODE REVIEW

**Comment by Teklad** [comment]
Alright, so I've been looking at this a while.  I **really** like the idea of having this feature.  However, I believe that use of system() in this case will cause way to much forking.

Is there any way I could get you to implement the sound playing via a library?  There are a multitude of ways to do it, for example:
https://gist.github.com/maxammann/52d6b65b42d8ce23512a

We'll probably need to make this feature optional as well due to the extra build requirements, but I can add all that stuff here on my end.

**Comment by Teklad** [comment]
Btw, you'll want to put the sound playing functions in the util folder, probably.

**Comment by w3bn00b** [comment]
@Teklad so.. i manage to make audio class
but im still getting error when compiling
also searched google but yeah... im not familiar with cmake

```
CMakeFiles/horker.dir/features/fvisual.cpp.o: In function `audio::play(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)':
fvisual.cpp:(.text._ZN5audio4playENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZN5audio4playENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0x4f): undefined reference to `sf_open'
fvisual.cpp:(.text._ZN5audio4playENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZN5audio4playENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0x58): undefined reference to `ao_initialize'
fvisual.cpp:(.text._ZN5audio4playENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZN5audio4playENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0x5d): undefined reference to `ao_default_driver_id'
fvisual.cpp:(.text._ZN5audio4playENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZN5audio4playENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0xf4): undefined reference to `ao_open_live'
fvisual.cpp:(.text._ZN5audio4playENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZN5audio4playENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0x154): undefined reference to `sf_read_short'
fvisual.cpp:(.text._ZN5audio4playENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZN5audio4playENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0x172): undefined reference to `ao_play'
fvisual.cpp:(.text._ZN5audio4playENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZN5audio4playENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0x1a2): undefined reference to `audio::cancel_playback'
CMakeFiles/horker.dir/features/fvisual.cpp.o: In function `audio::on_cancel_playback(int)':
fvisual.cpp:(.text._ZN5audio18on_cancel_playbackEi[_ZN5audio18on_cancel_playbackEi]+0x13): undefined reference to `audio::cancel_playback'
CMakeFiles/horker.dir/features/fvisual.cpp.o: In function `audio::clean(ao_device*, SNDFILE_tag*)':
fvisual.cpp:(.text._ZN5audio5cleanEP9ao_deviceP11SNDFILE_tag[_ZN5audio5cleanEP9ao_deviceP11SNDFILE_tag]+0x18): undefined reference to `ao_close'
fvisual.cpp:(.text._ZN5audio5cleanEP9ao_deviceP11SNDFILE_tag[_ZN5audio5cleanEP9ao_deviceP11SNDFILE_tag]+0x24): undefined reference to `sf_close'
fvisual.cpp:(.text._ZN5audio5cleanEP9ao_deviceP11SNDFILE_tag[_ZN5audio5cleanEP9ao_deviceP11SNDFILE_tag]+0x29): undefined reference to `ao_shutdown'
```

**Comment by w3bn00b** [comment]
current src/CMakeLists.txt
```
include_directories(/usr/lib/x86_64-linux-gnu)
link_directories(/usr/lib/x86_64-linux-gnu)

if (NVCtrlLib_FOUND)
    set (USE_NVIDIA 1)
endif()

configure_file(defines.h.in defines.h @ONLY)

add_executable(horker
    features/faim.cpp
    features/fbase.cpp
    features/fglow.cpp
    features/fvisual.cpp
    sdk/centitylist.cpp
    utils/audio.h
    hwctrl.cpp
    helper.cpp
    config.cpp
    engine.cpp
    main.cpp
    offsets.cpp
    process.cpp
    )

target_link_libraries(horker
    ${X11_LIBRARIES}
    ${X11_XTest_LIB}
    ${NVCtrlLib_LIBRARY}
    Threads::Threads
    sndfile
    )

target_include_directories(horker PRIVATE
    ${CMAKE_CURRENT_BINARY_DIR}
    ${NVCtrlLib_INCLUDE_DIR}
)
set_property(TARGET horker PROPERTY CXX_STANDARD 11)
```

**Comment by w3bn00b** [comment]
now what i have to do is adding libsndfile to cmakelist :(

**Comment by Teklad** [comment]
Undefined reference is almost always a linker error.

This means you probably need to add something to 'target_link_libraries' in the CMakeLists.txt.  There are in fact cmake modules laying around the web that make this stuff easier.

Give me a bit and I'll write a sound playing module for you to use.  I do have some tips as far as the code goes though.

```cpp
// Please follow code conventions of upper-case class/function names if you can remember. :)
class audio
{
public:
    int play(std::string filename);

private:
    // This will cause undefined references unless you define in a .cpp file somewhere the following:
    // int audio::cancel_playback;
    // Usually at the top or the bottom of a cpp file.
    static int cancel_playback;

    // Why are all of these static?  Try to avoid the use of statically defined header functions unless they're
    // actually needed
    static void on_cancel_playback(int sig);
    static void clean(ao_device *device, SNDFILE *file);
    // ao_device and SNDFILE could probably be member variables
};
// These definitions could probably go in their own cpp file
inline int audio::play(std::string filename)
```

As a programmer you should make a point to always ask yourself "How can I make this better?"  A larger majority of my time is spent researching different ways to implement things, better programming practices, etc.

**Pull request closed without merging**
