### PR TITLE
Added build script

### PR DESCRIPTION
**Pull request by w3bn00b**
well, im so lazy to build manually

### CODE REVIEW

**Comment by w3bn00b** [comment]
ah typo on commit msg :(

**Comment by Teklad** [comment]
You should be able to chmod +x the file before pushing.  That'll save at least one build step.  Alternatively you can change the build step to:
```bash
sh ./build
```

Whichever you prefer.

**Comment by Teklad** [comment]
Might as well throw a run script into this PR as well if you want. :-P

**Comment by w3bn00b** [comment]
nice :)
will change asap

**Pull request closed without merging**
